INSERT INTO public.recetas (producto_id, insumo_id, cantidad)
SELECT p.id, i.id, r.cantidad
FROM (VALUES
  ('Mojito Cubano', 'Ron blanco Mitjans', 100),
  ('Mojito Cubano', 'Limón (jugo)', 100),
  ('Mojito Cubano', 'Azúcar', 130),
  ('Mojito Cubano', 'Menta', 3),
  ('Mojito Cubano', 'Hielo cubo', 13),
  ('Mojito Cubano', 'Gaseosa ginger ale', 650),
  ('Mojito Blue', 'Ron blanco Mitjans', 100),
  ('Mojito Blue', 'Limón (jugo)', 150),
  ('Mojito Blue', 'Azúcar', 130),
  ('Mojito Blue', 'Menta', 3),
  ('Mojito Blue', 'Ron de curacao Mitjans', 150),
  ('Mojito Blue', 'Hielo cubo', 13),
  ('Mojito Blue', 'Gaseosa ginger ale', 500),
  ('Mojito Black', 'Vodka black Eristoff', 150),
  ('Mojito Black', 'Limón (jugo)', 150),
  ('Mojito Black', 'Azúcar', 130),
  ('Mojito Black', 'Menta', 3),
  ('Mojito Black', 'Hielo cubo', 13),
  ('Mojito Black', 'Gaseosa ginger ale', 500),
  ('Mojito Frambuesa', 'Ron blanco Mitjans', 100),
  ('Mojito Frambuesa', 'Limón (jugo)', 100),
  ('Mojito Frambuesa', 'Azúcar', 130),
  ('Mojito Frambuesa', 'Menta', 3),
  ('Mojito Frambuesa', 'Pulpa de frambuesa', 75),
  ('Mojito Frambuesa', 'Hielo cubo', 13),
  ('Mojito Frambuesa', 'Gaseosa ginger ale', 500),
  ('Mojito Frutilla', 'Ron blanco Mitjans', 100),
  ('Mojito Frutilla', 'Limón (jugo)', 100),
  ('Mojito Frutilla', 'Azúcar', 130),
  ('Mojito Frutilla', 'Menta', 3),
  ('Mojito Frutilla', 'Pulpa de frutilla', 75),
  ('Mojito Frutilla', 'Hielo cubo', 13),
  ('Mojito Frutilla', 'Gaseosa ginger ale', 500),
  ('Mojito Berries', 'Ron blanco Mitjans', 100),
  ('Mojito Berries', 'Limón (jugo)', 100),
  ('Mojito Berries', 'Azúcar', 130),
  ('Mojito Berries', 'Menta', 3),
  ('Mojito Berries', 'Pulpa de berries', 75),
  ('Mojito Berries', 'Hielo cubo', 13),
  ('Mojito Berries', 'Gaseosa ginger ale', 500),
  ('Mojito Mango', 'Ron blanco Mitjans', 100),
  ('Mojito Mango', 'Limón (jugo)', 100),
  ('Mojito Mango', 'Azúcar', 130),
  ('Mojito Mango', 'Menta', 3),
  ('Mojito Mango', 'Pulpa de mango', 75),
  ('Mojito Mango', 'Hielo cubo', 13),
  ('Mojito Mango', 'Gaseosa ginger ale', 500),
  ('Mojito Maracuya', 'Ron blanco Mitjans', 100),
  ('Mojito Maracuya', 'Limón (jugo)', 100),
  ('Mojito Maracuya', 'Azúcar', 130),
  ('Mojito Maracuya', 'Menta', 3),
  ('Mojito Maracuya', 'Pulpa de maracuya', 75),
  ('Mojito Maracuya', 'Hielo cubo', 13),
  ('Mojito Maracuya', 'Gaseosa ginger ale', 500),
  ('Mojito Piña', 'Ron blanco Mitjans', 100),
  ('Mojito Piña', 'Limón (jugo)', 100),
  ('Mojito Piña', 'Azúcar', 130),
  ('Mojito Piña', 'Menta', 3),
  ('Mojito Piña', 'Pulpa de piña', 75),
  ('Mojito Piña', 'Hielo cubo', 13),
  ('Mojito Piña', 'Gaseosa ginger ale', 500),
  ('Mojito Chirimoya', 'Ron blanco Mitjans', 100),
  ('Mojito Chirimoya', 'Limón (jugo)', 100),
  ('Mojito Chirimoya', 'Azúcar', 130),
  ('Mojito Chirimoya', 'Menta', 3),
  ('Mojito Chirimoya', 'Pulpa de chirimoya', 75),
  ('Mojito Chirimoya', 'Hielo cubo', 13),
  ('Mojito Chirimoya', 'Gaseosa ginger ale', 500),
  ('Mojito Coco', 'Ron de coco', 100),
  ('Mojito Coco', 'Limón (jugo)', 100),
  ('Mojito Coco', 'Azúcar', 130),
  ('Mojito Coco', 'Menta', 3),
  ('Mojito Coco', 'Pulpa de coco', 125),
  ('Mojito Coco', 'Hielo cubo', 13),
  ('Mojito Coco', 'Gaseosa ginger ale', 500),
  ('Mojito Cubano S/A', 'Limón (jugo)', 100),
  ('Mojito Cubano S/A', 'Azúcar', 130),
  ('Mojito Cubano S/A', 'Menta', 3),
  ('Mojito Cubano S/A', 'Hielo cubo', 13),
  ('Mojito Cubano S/A', 'Gaseosa ginger ale', 650),
  ('Mojito Frambuesa S/A', 'Limón (jugo)', 100),
  ('Mojito Frambuesa S/A', 'Azúcar', 130),
  ('Mojito Frambuesa S/A', 'Menta', 3),
  ('Mojito Frambuesa S/A', 'Pulpa de frambuesa', 75),
  ('Mojito Frambuesa S/A', 'Hielo cubo', 13),
  ('Mojito Frambuesa S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Frutilla S/A', 'Limón (jugo)', 100),
  ('Mojito Frutilla S/A', 'Azúcar', 130),
  ('Mojito Frutilla S/A', 'Menta', 3),
  ('Mojito Frutilla S/A', 'Pulpa de frutilla', 75),
  ('Mojito Frutilla S/A', 'Hielo cubo', 13),
  ('Mojito Frutilla S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Berries S/A', 'Limón (jugo)', 100),
  ('Mojito Berries S/A', 'Azúcar', 130),
  ('Mojito Berries S/A', 'Menta', 3),
  ('Mojito Berries S/A', 'Pulpa de berries', 75),
  ('Mojito Berries S/A', 'Hielo cubo', 13),
  ('Mojito Berries S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Mango S/A', 'Limón (jugo)', 100),
  ('Mojito Mango S/A', 'Azúcar', 130),
  ('Mojito Mango S/A', 'Menta', 3),
  ('Mojito Mango S/A', 'Pulpa de mango', 75),
  ('Mojito Mango S/A', 'Hielo cubo', 13),
  ('Mojito Mango S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Maracuya S/A', 'Limón (jugo)', 100),
  ('Mojito Maracuya S/A', 'Azúcar', 130),
  ('Mojito Maracuya S/A', 'Menta', 3),
  ('Mojito Maracuya S/A', 'Pulpa de maracuya', 75),
  ('Mojito Maracuya S/A', 'Hielo cubo', 13),
  ('Mojito Maracuya S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Piña S/A', 'Limón (jugo)', 100),
  ('Mojito Piña S/A', 'Azúcar', 130),
  ('Mojito Piña S/A', 'Menta', 3),
  ('Mojito Piña S/A', 'Pulpa de piña', 75),
  ('Mojito Piña S/A', 'Hielo cubo', 13),
  ('Mojito Piña S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Chirimoya S/A', 'Limón (jugo)', 100),
  ('Mojito Chirimoya S/A', 'Azúcar', 130),
  ('Mojito Chirimoya S/A', 'Menta', 3),
  ('Mojito Chirimoya S/A', 'Pulpa de chirimoya', 75),
  ('Mojito Chirimoya S/A', 'Hielo cubo', 13),
  ('Mojito Chirimoya S/A', 'Gaseosa ginger ale', 600),
  ('Mojito Coco S/A', 'Limón (jugo)', 100),
  ('Mojito Coco S/A', 'Azúcar', 130),
  ('Mojito Coco S/A', 'Menta', 3),
  ('Mojito Coco S/A', 'Pulpa de coco', 125),
  ('Mojito Coco S/A', 'Hielo cubo', 13),
  ('Mojito Coco S/A', 'Gaseosa ginger ale', 500),
  ('Piña Colada', 'Ron blanco Mitjans', 100),
  ('Piña Colada', 'Azúcar', 130),
  ('Piña Colada', 'Pulpa de piña', 200),
  ('Piña Colada', 'Hielo frappe', 600),
  ('Piña Colada', 'Leche', 500),
  ('Chirimoya Colada', 'Ron blanco Mitjans', 100),
  ('Chirimoya Colada', 'Azúcar', 130),
  ('Chirimoya Colada', 'Pulpa de chirimoya', 200),
  ('Chirimoya Colada', 'Hielo frappe', 600),
  ('Chirimoya Colada', 'Leche', 500),
  ('Frambuesa Colada', 'Ron blanco Mitjans', 100),
  ('Frambuesa Colada', 'Azúcar', 130),
  ('Frambuesa Colada', 'Pulpa de frambuesa', 200),
  ('Frambuesa Colada', 'Hielo frappe', 600),
  ('Frambuesa Colada', 'Leche', 500),
  ('Frutilla Colada', 'Ron blanco Mitjans', 100),
  ('Frutilla Colada', 'Azúcar', 130),
  ('Frutilla Colada', 'Pulpa de frutilla', 200),
  ('Frutilla Colada', 'Hielo frappe', 600),
  ('Frutilla Colada', 'Leche', 500),
  ('Berries Colada', 'Ron blanco Mitjans', 100),
  ('Berries Colada', 'Azúcar', 130),
  ('Berries Colada', 'Pulpa de berries', 200),
  ('Berries Colada', 'Hielo frappe', 600),
  ('Berries Colada', 'Leche', 500),
  ('Mango Colada', 'Ron blanco Mitjans', 100),
  ('Mango Colada', 'Azúcar', 130),
  ('Mango Colada', 'Pulpa de mango', 200),
  ('Mango Colada', 'Hielo frappe', 600),
  ('Mango Colada', 'Leche', 500),
  ('Maracuya Colada', 'Ron blanco Mitjans', 100),
  ('Maracuya Colada', 'Azúcar', 130),
  ('Maracuya Colada', 'Pulpa de maracuya', 200),
  ('Maracuya Colada', 'Hielo frappe', 600),
  ('Maracuya Colada', 'Leche', 500),
  ('Piña Colada S/A', 'Azúcar', 130),
  ('Piña Colada S/A', 'Pulpa de piña', 200),
  ('Piña Colada S/A', 'Hielo frappe', 700),
  ('Piña Colada S/A', 'Leche', 500),
  ('Chirimoya Colada S/A', 'Azúcar', 130),
  ('Chirimoya Colada S/A', 'Pulpa de chirimoya', 200),
  ('Chirimoya Colada S/A', 'Hielo frappe', 700),
  ('Chirimoya Colada S/A', 'Leche', 500),
  ('Frambuesa Colada S/A', 'Azúcar', 130),
  ('Frambuesa Colada S/A', 'Pulpa de frambuesa', 200),
  ('Frambuesa Colada S/A', 'Hielo frappe', 700),
  ('Frambuesa Colada S/A', 'Leche', 500),
  ('Frutilla Colada S/A', 'Azúcar', 130),
  ('Frutilla Colada S/A', 'Pulpa de frutilla', 200),
  ('Frutilla Colada S/A', 'Hielo frappe', 700),
  ('Frutilla Colada S/A', 'Leche', 500),
  ('Berries Colada S/A', 'Azúcar', 130),
  ('Berries Colada S/A', 'Pulpa de berries', 200),
  ('Berries Colada S/A', 'Hielo frappe', 700),
  ('Berries Colada S/A', 'Leche', 500),
  ('Mango Colada S/A', 'Azúcar', 130),
  ('Mango Colada S/A', 'Pulpa de mango', 200),
  ('Mango Colada S/A', 'Hielo frappe', 700),
  ('Mango Colada S/A', 'Leche', 500),
  ('Maracuya Colada S/A', 'Azúcar', 130),
  ('Maracuya Colada S/A', 'Pulpa de maracuya', 200),
  ('Maracuya Colada S/A', 'Hielo frappe', 700),
  ('Maracuya Colada S/A', 'Leche', 500)
) AS r(producto_nombre, insumo_nombre, cantidad)
JOIN public.productos p ON p.nombre = r.producto_nombre
JOIN public.insumos i ON i.nombre = r.insumo_nombre
ON CONFLICT (producto_id, insumo_id) DO UPDATE SET cantidad = EXCLUDED.cantidad;